trigger:
  branches:
    include:
      - '*'

pr:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: DockerCompose@1
  displayName: Run unit tests
  inputs:
    dockerComposeFile: 'docker-compose.test.yaml'
