version: '2'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - CONCIERGE_ALLOWED_HOSTS=['*']
      - CONCIERGE_SECRET_KEY=qWxPJrZCLeHZraNTWjEKHdJJxJyho8
      - CONCIERGE_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SEND_SUSPICIOUS_BEHAVIOR_WARNINGS=True
    ports:
      - "80:8000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./media:/app/media
  redis:
    image: redis:7.2
    restart: always
