version: '2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
      - DEBUG=True
      - SECURE_SESSION=False
      - CONCIERGE_ALLOWED_HOSTS='*'
      - CONCIERGE_SECRET_KEY=qWxPJrZCLeHZraNTWjEKHdJJxJyho8
      - CONCIERGE_DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - SEND_SUSPICIOUS_BEHAVIOR_WARNINGS=True
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./media:/app/media
      - ./api:/app/api
      - ./core:/app/core
      - ./emailvalidator:/app/emailvalidator
      - ./locale:/app/locale
  redis:
    image: redis